name = "fox1-ai"
main = "worker.js"
compatibility_date = "2024-01-01"
keep_vars = true

[[d1_databases]]
binding = "DB"
database_name = "fox-ai-db"
database_id = "af119c1d-6f40-41d3-aab0-590cdce0462e"

# إضافة ربط الذكاء الاصطناعي هنا
[ai]
binding = "AI"