import { id, now, assertStatus, TASK_STATUS, STEP_STATUS, stepRecord, taskRecord, eventRecord } from './contracts.js';

const TRANSITIONS={received:['clarifying','planning','cancelled'],clarifying:['received','planning','cancelled'],planning:['awaiting_approval','failed'],awaiting_approval:['running','cancelled','planning'],running:['verifying','paused','failed','recovering','completed'],verifying:['running','completed','recovering'],recovering:['running','planning','failed'],paused:['running','cancelled','recovering'],completed:[],failed:['planning','running'],cancelled:[]};
export function canTransition(from,to){return from===to||!!TRANSITIONS[from]?.includes(to);}
export function transition(record,to){assertStatus(to,TASK_STATUS,'task status');if(!canTransition(record.status,to))throw new Error(`انتقال غير مسموح: ${record.status} -> ${to}`);return {...record,status:to,updatedAt:now()};}
export function createTask(input){return taskRecord(input);}
export function createPlan(task,{goal=task.goal,steps=[]}={}){if(!steps.length)throw new Error('الخطة تحتاج خطوة واحدة على الأقل');return {id:id('plan'),taskId:task.id,version:1,goal,approvalStatus:'pending',createdAt:now(),steps:steps.map((s,i)=>stepRecord(s,i))};}
export function approvePlan(task,plan){if(task.status==='planning')task=transition(task,'awaiting_approval');if(task.status!=='awaiting_approval')throw new Error('الخطة ليست بانتظار الموافقة');return {task:transition(task,'running'),plan:{...plan,approvalStatus:'approved',steps:plan.steps.map((s,i)=>i===0?{...s,status:'running'}:s)}};}
export function startPlanning(task){return transition(task,'planning');}
export function startStep(task,plan,stepId){const step=plan.steps.find(x=>x.id===stepId);if(!step)throw new Error('الخطوة غير موجودة');return {task:transition(task,'running'),plan:{...plan,steps:plan.steps.map(x=>x.id===stepId?{...x,status:'running'}:x)}};}
export function completeStep(task,plan,stepId,output,evidence=[]){const i=plan.steps.findIndex(x=>x.id===stepId);if(i<0)throw new Error('الخطوة غير موجودة');const steps=plan.steps.map((x,n)=>n===i?{...x,status:'completed',output,evidence,completedAt:now()}:x);const next=steps.find(x=>x.status==='pending');const nextSteps=next?steps.map(x=>x.id===next.id?{...x,status:'running'}:x):steps;return {task:transition(task,next?'running':'completed'),plan:{...plan,steps:nextSteps}};}
export function failStep(task,plan,stepId,error){const step=plan.steps.find(x=>x.id===stepId);if(!step)throw new Error('الخطوة غير موجودة');const attempts=(step.attempts||0)+1;const retry=attempts<3;return {task:transition(task,retry?'recovering':'failed'),plan:{...plan,steps:plan.steps.map(x=>x.id===stepId?{...x,status:retry?'retrying':'failed',attempts,error}:x)},retry};}
export function retryStep(task,plan,stepId){const step=plan.steps.find(x=>x.id===stepId);if(!step||step.status!=='retrying')throw new Error('الخطوة ليست قابلة للإعادة');return {task:transition(task,'running'),plan:{...plan,steps:plan.steps.map(x=>x.id===stepId?{...x,status:'running'}:x)}};}
export function taskEvent(task,type,payload={}){return eventRecord({taskId:task.id,type,payload});}
export function memoryTaskStore(){const tasks=new Map(),plans=new Map(),events=new Map();return {async saveTask(x){tasks.set(x.id,structuredClone(x));return x},async getTask(id){return structuredClone(tasks.get(id)||null)},async savePlan(x){plans.set(x.id,structuredClone(x));return x},async getPlan(id){return structuredClone(plans.get(id)||null)},async appendEvent(x){const a=events.get(x.taskId)||[];a.push(structuredClone(x));events.set(x.taskId,a);return x},async listEvents(id){return structuredClone(events.get(id)||[])}};}
