import { publicCatalog, getModel, chooseModel } from './src/catalog.js';
import { routeCompletion, ProviderError } from './src/providers.js';
import { d1ContextStore, contextPacket, renderHandoff, mergeContext, createContextEvent } from './src/context.js';
import { createTask, startPlanning, createPlan, approvePlan, completeStep, failStep, retryStep, taskEvent } from './src/tasks.js';
import { detectToolProposal, approvalRecord, experimentRecord, dispatchExperiment, verifyResult, retryExperiment, verifyWebhook } from './src/tools.js';
import { multimodalMessages, modelCapabilities } from './src/media.js';

const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8',...CORS}});
const text=x=>String(x||'').trim();

async function schema(env){const q=[
'CREATE TABLE IF NOT EXISTS context_state (chat_id TEXT PRIMARY KEY, state_json TEXT NOT NULL, updated_at INTEGER NOT NULL)',
'CREATE TABLE IF NOT EXISTS context_events (id TEXT PRIMARY KEY, chat_id TEXT NOT NULL, type TEXT NOT NULL, payload_json TEXT NOT NULL, created_at INTEGER NOT NULL)',
'CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, chat_id TEXT NOT NULL, task_json TEXT NOT NULL, plan_json TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)',
'CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL)',
'CREATE TABLE IF NOT EXISTS experiments (id TEXT PRIMARY KEY, chat_id TEXT NOT NULL, command TEXT NOT NULL, status TEXT NOT NULL, output TEXT NOT NULL, exit_code INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)',
'CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY, title TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)',
'CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, chat_id TEXT NOT NULL, role TEXT NOT NULL, content TEXT NOT NULL, model_id TEXT, created_at INTEGER NOT NULL)',
	'CREATE INDEX IF NOT EXISTS idx_messages_chat ON messages(chat_id, created_at ASC)',
	'CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value_json TEXT NOT NULL, updated_at INTEGER NOT NULL)',
	'CREATE TABLE IF NOT EXISTS tool_budgets (chat_id TEXT PRIMARY KEY, granted INTEGER NOT NULL, used INTEGER NOT NULL, updated_at INTEGER NOT NULL)',
	'CREATE TABLE IF NOT EXISTS conversation_files (id TEXT PRIMARY KEY, chat_id TEXT NOT NULL, name TEXT NOT NULL, mime TEXT NOT NULL, size INTEGER NOT NULL, content_text TEXT, data_url TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)',
	'CREATE INDEX IF NOT EXISTS idx_files_chat ON conversation_files(chat_id,created_at DESC)',
		'CREATE TABLE IF NOT EXISTS task_control (task_id TEXT PRIMARY KEY, status TEXT NOT NULL, updated_at INTEGER NOT NULL)'];for(const sql of q)await env.DB.prepare(sql).run();}
async function toolProposal(env,b){const proposal=detectToolProposal(b.text||b.content||'');return json({proposal});}
async function runTool(env,b){const proposal=b.proposal;if(!proposal)return json({error:'proposal مطلوب'},400);if(!b.chatId)return json({error:'chatId مطلوب'},400);let budget=await env.DB.prepare('SELECT chat_id,granted,used,updated_at FROM tool_budgets WHERE chat_id=?').bind(b.chatId).first();const requested=Math.max(1,Math.min(10,Number(b.approvalBudget)||5));if(b.approved!==true)return json({needsApproval:true,reason:'لا يمكن تشغيل الطرفية دون موافقة',proposal,budget:budget?{granted:budget.granted,used:budget.used,remaining:Math.max(0,budget.granted-budget.used)}:null},403);if(!budget){const timestamp=Date.now();await env.DB.prepare('INSERT INTO tool_budgets (chat_id,granted,used,updated_at) VALUES (?,?,?,?)').bind(b.chatId,requested,0,timestamp).run();budget={chat_id:b.chatId,granted:requested,used:0,updated_at:timestamp};}else if(Number(budget.used)>=Number(budget.granted)){const renewal=Math.max(1,Math.min(10,Number(b.renewBudget)||0));if(!renewal)return json({needsApproval:true,reason:'انتهت حصة تنفيذ الطرفية. اختر 5 أو 10 عمليات جديدة.',proposal,budget:{granted:budget.granted,used:budget.used,remaining:0}},403);const timestamp=Date.now();await env.DB.prepare('UPDATE tool_budgets SET granted=?,used=0,updated_at=? WHERE chat_id=?').bind(renewal,timestamp,b.chatId).run();budget={...budget,granted:renewal,used:0,updated_at:timestamp};}const remaining=Number(budget.granted)-Number(budget.used);const approval=approvalRecord({proposalId:proposal.id,approved:true,scope:`budget_${budget.granted}`});const experiment=experimentRecord({chatId:b.chatId,proposal,approval});await env.DB.prepare('UPDATE tool_budgets SET used=used+1,updated_at=? WHERE chat_id=?').bind(Date.now(),b.chatId).run();await env.DB.prepare('INSERT INTO experiments (id,chat_id,command,status,output,exit_code,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').bind(experiment.id,experiment.chatId,experiment.command,experiment.status,'',null,experiment.createdAt,experiment.updatedAt).run();const dispatched=await dispatchExperiment(env,experiment);await env.DB.prepare('UPDATE experiments SET status=?,updated_at=? WHERE id=?').bind(dispatched.status,dispatched.updatedAt,dispatched.id).run();return json({experiment:dispatched,budget:{granted:budget.granted,used:Number(budget.used)+1,remaining:remaining-1}});}
async function toolBudget(env,b){if(!b.chatId)return json({error:'chatId مطلوب'},400);const r=await env.DB.prepare('SELECT chat_id,granted,used,updated_at FROM tool_budgets WHERE chat_id=?').bind(b.chatId).first();return json({budget:r?{granted:r.granted,used:r.used,remaining:Math.max(0,Number(r.granted)-Number(r.used)),updatedAt:r.updated_at}:{granted:0,used:0,remaining:0}});}
async function workspaceStatus(env,b){if(!b.chatId)return json({error:'chatId مطلوب'},400);const files=await env.DB.prepare('SELECT id,name,mime,size,created_at FROM conversation_files WHERE chat_id=? ORDER BY created_at DESC LIMIT 100').bind(b.chatId).all(),experiments=await env.DB.prepare('SELECT id,command,status,exit_code,created_at,updated_at FROM experiments WHERE chat_id=? ORDER BY created_at DESC LIMIT 30').bind(b.chatId).all(),budget=await env.DB.prepare('SELECT granted,used,updated_at FROM tool_budgets WHERE chat_id=?').bind(b.chatId).first();return json({workspace:{type:'fox-session',persistentFiles:true,terminal:'github-actions',storage:env.FILES?'r2+d1':'d1-metadata',files:files.results||[],experiments:experiments.results||[],budget:budget?{granted:budget.granted,used:budget.used,remaining:Math.max(0,Number(budget.granted)-Number(budget.used))}:{granted:0,used:0,remaining:0}}});}
async function receiveToolResult(env,request){const raw=await request.text(),sig=request.headers.get('X-FOX-Signature')||'';if(!await verifyWebhook(raw,sig,env.HMAC_SECRET))return json({error:'توقيع النتيجة غير صالح'},403);const b=JSON.parse(raw),row=await env.DB.prepare('SELECT id,chat_id,command,status,output,exit_code,created_at,updated_at FROM experiments WHERE id=?').bind(b.experimentId).first();if(!row)return json({error:'التجربة غير موجودة'},404);const result=verifyResult({...row,id:row.id},{output:b.output||'',exitCode:b.exit_code??1});await env.DB.prepare('UPDATE experiments SET status=?,output=?,exit_code=?,updated_at=? WHERE id=?').bind(result.status,result.output,result.exitCode,result.updatedAt,result.id).run();return json({success:true,experiment:result});}
async function session(env,token){if(!env.ACCESS_PASSWORD)return true;if(!token)return false;const r=await env.DB.prepare('SELECT expires_at FROM sessions WHERE token = ?').bind(token).first();return !!r&&Number(r.expires_at)>Date.now();}
async function login(env,body){if(env.ACCESS_PASSWORD&&body.accessPassword!==env.ACCESS_PASSWORD)return json({error:'كلمة المرور غير صحيحة',authRequired:true},401);const token=crypto.randomUUID(),now=Date.now();await env.DB.prepare('INSERT INTO sessions (token,created_at,expires_at) VALUES (?,?,?)').bind(token,now,now+86400000).run();return json({success:true,token,expiresAt:now+86400000});}
function system(){return 'أنت FOX AI، وكيل شخصي دقيق. مالكك ومطورك هو عبدالرحيم. إذا سُئلت: من صاحبك أو من طورك أو من أنشأك، فأجب بوضوح: أنا FOX AI، طوّرني ويمتلكني عبدالرحيم. لا تدّع تنفيذ شيء لم تنفذه. استخدم العربية عند مخاطبتك بالعربية. افصل الحقائق عن الاقتراحات.';}
async function persistMessage(env,chatId,role,content,modelId=null){const t=Date.now();await env.DB.prepare('INSERT INTO messages (id,chat_id,role,content,model_id,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),chatId,role,String(content||''),modelId,t).run();await env.DB.prepare('INSERT INTO conversations (id,title,created_at,updated_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET updated_at=?').bind(chatId,String(content||'').slice(0,80)||'محادثة جديدة',t,t,t).run();}
async function persistFiles(env,chatId,files=[]){for(const f of Array.isArray(files)?files:[]){const id=crypto.randomUUID(),name=text(f.name).slice(0,180)||'file',mime=text(f.mime||f.type).slice(0,120)||'application/octet-stream',size=Math.max(0,Number(f.size)||0),content=f.text!=null?String(f.text).slice(0,120000):null;let data=mime.startsWith('image/')&&String(f.data||'').length<=700000?String(f.data):null;if(env.FILES&&f.data){const raw=String(f.data),match=raw.match(/^data:([^;]+);base64,(.*)$/s);if(match){const bytes=Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0));await env.FILES.put(`conversations/${chatId}/${id}-${name}`,bytes,{httpMetadata:{contentType:mime}});data=`r2:conversations/${chatId}/${id}-${name}`;}}await env.DB.prepare('INSERT INTO conversation_files (id,chat_id,name,mime,size,content_text,data_url,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,chatId,name,mime,size,content,data,Date.now(),Date.now()).run();}}
async function loadMessages(env,chatId){const r=await env.DB.prepare('SELECT role,content,model_id,created_at FROM messages WHERE chat_id=? ORDER BY created_at ASC LIMIT 100').bind(chatId).all();return (r.results||[]).map(x=>({role:x.role,content:x.content,model:x.model_id||null,createdAt:x.created_at}));}
async function chat(env,b){if(!b.chatId||!Array.isArray(b.messages)||!b.messages.length)return json({error:'chatId والرسائل مطلوبان'},400);const store=d1ContextStore(env.DB),state=await store.get(b.chatId),recent=b.messages.slice(-14),requested=getModel(b.model||chooseModel(recent.at(-1)?.content).id),hasImage=(b.attachments||[]).some(x=>String(x.mime||x.type||'').startsWith('image/')),model=hasImage&&requested.kind!=='vision'?getModel('cf-llama-vision'):requested,packet=contextPacket(state,recent),media=multimodalMessages([{role:'user',content:recent.at(-1)?.content||''}],b.attachments||[],model.id),result=await routeCompletion(env,model.id,[{role:'system',content:system()+'\n\n'+renderHandoff(state,recent)},...packet.recent.slice(0,-1),...media.messages],{maxTokens:4096});const answer=result.text;const last=text(recent.at(-1)?.content);await persistFiles(env,b.chatId,b.attachments||[]);await persistMessage(env,b.chatId,'user',last,null);await persistMessage(env,b.chatId,'assistant',answer,result.actual.id);const patch={summary:last.slice(0,500),facts:state.facts,decisions:state.decisions,next:'متابعة طلب المستخدم',constraints:state.constraints};const next=mergeContext(state,patch);await store.put(b.chatId,next);await store.appendEvent(createContextEvent(b.chatId,'model_called',{requested:model.id,actual:result.actual.id,fallback:result.fallback,media:!!b.attachments?.length}));await store.appendEvent(createContextEvent(b.chatId,'context_updated',{revision:next.revision}));return json({response:answer,model:result.actual,requestedModel:requested,pendingExecution:detectToolProposal(answer),unsupportedAttachments:media.unsupported,memory:renderHandoff(next,[]),trace:{provider:result.actual.provider,model:result.actual.model,fallback:result.fallback,contextMessages:packet.recent.length,media:!!b.attachments?.length,memoryUpdated:true}});}
async function plan(env,b){if(!b.chatId||!text(b.task))return json({error:'chatId و task مطلوبان'},400);const state=await d1ContextStore(env.DB).get(b.chatId),model=getModel(b.model||chooseModel(b.task).id),prompt=`أنشئ خطة JSON فقط بالشكل {"goal":"...","steps":[{"title":"...","description":"...","verification":"...","tool":"none"}]}. المهمة: ${b.task}\nالسياق: ${renderHandoff(state,[])}`;const r=await routeCompletion(env,model.id,[{role:'system',content:system()+' لا تنفذ شيئًا. أعد JSON صحيحًا فقط.'},{role:'user',content:prompt}],{maxTokens:1800,temperature:.1});let raw=r.text.match(/\{[\s\S]*\}/)?.[0]||'{}',parsed;try{parsed=JSON.parse(raw)}catch{parsed={goal:b.task,steps:[{title:'تحليل المتطلبات',description:b.task,verification:'وجود خطة',tool:'none'}]}};const task=startPlanning(createTask({conversationId:b.chatId,goal:parsed.goal||b.task}));const plan=createPlan(task,{goal:parsed.goal||b.task,steps:Array.isArray(parsed.steps)&&parsed.steps.length?parsed.steps:[{title:'تحليل المتطلبات',description:b.task,verification:'وجود خطة',tool:'none'}]});await env.DB.prepare('INSERT INTO tasks (id,chat_id,task_json,plan_json,created_at,updated_at) VALUES (?,?,?,?,?,?)').bind(task.id,b.chatId,JSON.stringify(task),JSON.stringify(plan),Date.now(),Date.now()).run();return json({task,plan,model:r.actual});}
async function getRun(env,b){const r=await env.DB.prepare('SELECT task_json,plan_json FROM tasks WHERE id=?').bind(b.runId).first();if(!r)return json({error:'المهمة غير موجودة'},404);return json({task:JSON.parse(r.task_json),plan:JSON.parse(r.plan_json)});}
async function getTaskControl(env,b){if(!b.taskId)return json({error:'taskId مطلوب'},400);const task=await env.DB.prepare('SELECT id,task_json,plan_json FROM tasks WHERE id=?').bind(b.taskId).first();if(!task)return json({error:'المهمة غير موجودة'},404);const control=await env.DB.prepare('SELECT task_id,status,updated_at FROM task_control WHERE task_id=?').bind(b.taskId).first();return json({task:JSON.parse(task.task_json),plan:task.plan_json?JSON.parse(task.plan_json):null,control:control||{task_id:b.taskId,status:JSON.parse(task.task_json).status,updated_at:null}});}
async function stepControl(env,b){if(!b.taskId||!b.stepId||!['start_step','complete_step','fail_step','retry_step'].includes(b.action))return json({error:'taskId و stepId وإجراء الخطوة مطلوبون'},400);const row=await env.DB.prepare('SELECT task_json,plan_json FROM tasks WHERE id=?').bind(b.taskId).first();if(!row)return json({error:'المهمة غير موجودة'},404);let task=JSON.parse(row.task_json),plan=JSON.parse(row.plan_json||'null');if(!plan)return json({error:'الخطة غير موجودة'},404);const control=await env.DB.prepare('SELECT status FROM task_control WHERE task_id=?').bind(b.taskId).first();if(['paused','cancelled'].includes(control?.status))return json({error:`المهمة ${control.status==='paused'?'متوقفة مؤقتًا':'ملغاة'}`},409);let result;if(b.action==='start_step'){if(task.status==='planning'||task.status==='awaiting_approval')result=approvePlan(task,plan);else result=startStep(task,plan,b.stepId);}else if(b.action==='complete_step')result=completeStep(task,plan,b.stepId,text(b.output)||'تمت الخطوة يدويًا',Array.isArray(b.evidence)?b.evidence:[]);else if(b.action==='fail_step')result=failStep(task,plan,b.stepId,text(b.error)||'فشلت الخطوة');else result=retryStep(task,plan,b.stepId);task=result.task;plan=result.plan;await env.DB.prepare('UPDATE tasks SET task_json=?,plan_json=?,updated_at=? WHERE id=?').bind(JSON.stringify(task),JSON.stringify(plan),Date.now(),b.taskId).run();return json({success:true,task,plan,retry:result.retry??false});}
async function getExperiment(env,b){if(!b.experimentId)return json({error:'experimentId مطلوب'},400);const r=await env.DB.prepare('SELECT id,chat_id,command,status,output,exit_code,created_at,updated_at FROM experiments WHERE id=?').bind(b.experimentId).first();if(!r)return json({error:'التجربة غير موجودة'},404);return json({experiment:{...r,exitCode:r.exit_code,createdAt:r.created_at,updatedAt:r.updated_at}});}
async function memory(env,b){if(!b.chatId)return json({error:'chatId مطلوب'},400);const store=d1ContextStore(env.DB);if(b.action==='memory_update'){const state=mergeContext(await store.get(b.chatId),{summary:text(b.content).slice(0,2000)});await store.put(b.chatId,state);return json({success:true,content:renderHandoff(state,[])});}const state=await store.get(b.chatId);return json({content:renderHandoff(state,[]),state});}
async function messages(env,b){if(!b.chatId)return json({error:'chatId مطلوب'},400);const files=await env.DB.prepare('SELECT id,name,mime,size,created_at FROM conversation_files WHERE chat_id=? ORDER BY created_at DESC').bind(b.chatId).all();return json({messages:await loadMessages(env,b.chatId),files:files.results||[]});}
async function searchAll(env,b){const q=text(b.query).slice(0,120);if(!q)return json({conversations:[],messages:[],files:[]});const like=`%${q}%`,chatId=b.chatId||null;const conversations=chatId?{results:[]} : await env.DB.prepare('SELECT id,title,updated_at FROM conversations WHERE title LIKE ? ORDER BY updated_at DESC LIMIT 30').bind(like).all();const messages=chatId?await env.DB.prepare('SELECT id,chat_id,role,content,created_at FROM messages WHERE chat_id=? AND content LIKE ? ORDER BY created_at DESC LIMIT 50').bind(chatId,like).all():await env.DB.prepare('SELECT id,chat_id,role,content,created_at FROM messages WHERE content LIKE ? ORDER BY created_at DESC LIMIT 50').bind(like).all();const files=chatId?await env.DB.prepare('SELECT id,chat_id,name,mime,size,content_text,created_at FROM conversation_files WHERE chat_id=? AND (name LIKE ? OR content_text LIKE ?) ORDER BY created_at DESC LIMIT 50').bind(chatId,like,like).all():await env.DB.prepare('SELECT id,chat_id,name,mime,size,content_text,created_at FROM conversation_files WHERE name LIKE ? OR content_text LIKE ? ORDER BY created_at DESC LIMIT 50').bind(like,like).all();return json({query:q,conversations:conversations.results||[],messages:messages.results||[],files:files.results||[]});}
async function settings(env,b){if(b.action==='settings_get'){const r=await env.DB.prepare('SELECT key,value_json FROM settings ORDER BY key').all();return json({settings:(r.results||[]).map(x=>({key:x.key,value:JSON.parse(x.value_json)}))});}if(!b.key)return json({error:'key مطلوب'},400);if(b.key.includes('API_KEY')||b.key.includes('TOKEN')||b.key.includes('PASSWORD'))return json({error:'المفاتيح السرية تُدار من Cloudflare Secrets ولا تُحفظ في D1'},400);await env.DB.prepare('INSERT INTO settings (key,value_json,updated_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET value_json=?,updated_at=?').bind(b.key,JSON.stringify(b.value??null),Date.now(),JSON.stringify(b.value??null),Date.now()).run();return json({success:true});}
async function conversationControl(env,b){if(!b.chatId)return json({error:'chatId مطلوب'},400);if(b.action==='rename_conversation'){const title=text(b.title).slice(0,120);if(!title)return json({error:'العنوان مطلوب'},400);await env.DB.prepare('UPDATE conversations SET title=?,updated_at=? WHERE id=?').bind(title,Date.now(),b.chatId).run();return json({success:true,title});}if(b.action==='delete_conversation'){await env.DB.prepare('DELETE FROM conversation_files WHERE chat_id=?').bind(b.chatId).run();await env.DB.prepare('DELETE FROM messages WHERE chat_id=?').bind(b.chatId).run();await env.DB.prepare('DELETE FROM context_state WHERE chat_id=?').bind(b.chatId).run();await env.DB.prepare('DELETE FROM context_events WHERE chat_id=?').bind(b.chatId).run();await env.DB.prepare('DELETE FROM conversations WHERE id=?').bind(b.chatId).run();return json({success:true});}return json({error:'إجراء محادثة غير معروف'},400);}
async function taskControl(env,b){if(!b.taskId)return json({error:'taskId مطلوب'},400);const row=await env.DB.prepare('SELECT task_json FROM tasks WHERE id=?').bind(b.taskId).first();if(!row)return json({error:'المهمة غير موجودة'},404);const status=b.action==='cancel_task'?'cancelled':b.action==='pause_task'?'paused':b.action==='resume_task'?'running':null;if(!status)return json({error:'إجراء تحكم غير معروف'},400);const timestamp=Date.now();await env.DB.prepare('INSERT INTO task_control (task_id,status,updated_at) VALUES (?,?,?) ON CONFLICT(task_id) DO UPDATE SET status=?,updated_at=?').bind(b.taskId,status,timestamp,status,timestamp).run();return json({success:true,taskId:b.taskId,status,updatedAt:timestamp});}
export default {async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{headers:CORS});const pathname=new URL(request.url).pathname;if(pathname==='/tool-result')return receiveToolResult(env,request);if(request.method==='GET'){if((pathname==='/'||pathname==='/index.html')&&env.ASSETS)return env.ASSETS.fetch(new Request(new URL('/index.html',request.url),request));return json({name:'FOX AI',status:'ready',version:'3.0.0'});}if(request.method!=='POST')return json({error:'Method not allowed'},405);try{await schema(env);const b=await request.json();if(b.action==='models')return json({models:publicCatalog()});if(b.action==='login')return login(env,b);if(!await session(env,b.sessionToken))return json({error:'الجلسة غير صالحة',authRequired:true},401);if(b.action==='chat')return chat(env,b);if(b.action==='get_messages')return messages(env,b);if(b.action==='search_all')return searchAll(env,b);if(b.action==='plan_task')return plan(env,b);if(b.action==='get_memory'||b.action==='memory_update')return memory(env,b);if(b.action==='get_run')return getRun(env,b);if(b.action==='get_task_control')return getTaskControl(env,b);if(b.action==='step_control')return stepControl(env,b);if(b.action==='get_experiment')return getExperiment(env,b);if(b.action==='tool_proposal')return toolProposal(env,b);if(b.action==='tool_budget')return toolBudget(env,b);if(b.action==='workspace_status')return workspaceStatus(env,b);if(b.action==='run_tool')return runTool(env,b);if(['settings_get','settings_set'].includes(b.action))return settings(env,b);if(['rename_conversation','delete_conversation'].includes(b.action))return conversationControl(env,b);if(['cancel_task','pause_task','resume_task'].includes(b.action))return taskControl(env,b);return json({error:'إجراء غير معروف'},400);}catch(e){console.error(e);const status=e instanceof ProviderError?e.status:500;return json({error:e.message||'خطأ داخلي',provider:e.provider||null,retryable:!!e.retryable},status);}}};
