import { getModel } from './catalog.js';
export class ProviderError extends Error { constructor(provider,message,status=502,retryable=false){super(message);this.name='ProviderError';this.provider=provider;this.status=status;this.retryable=retryable;} }
export function normalizeMessages(messages=[]){return messages.filter(Boolean).map(m=>({role:m.role==='model'?'assistant':m.role,content:typeof m.content==='string'||Array.isArray(m.content)?m.content:JSON.stringify(m.content)})).filter(m=>['system','user','assistant','tool'].includes(m.role));}
async function readResponse(r,provider){const d=await r.json().catch(()=>({}));if(!r.ok)throw new ProviderError(provider,String(d?.error?.message||d?.error||d?.message||`${provider} HTTP ${r.status}`),r.status,r.status===408||r.status===429||r.status>=500);return d;}
async function openAI({key,endpoint,model,messages,provider,options={}}){if(!key)throw new ProviderError(provider,`${provider} API key غير موجود في أسرار العامل`,401);const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model,messages:normalizeMessages(messages),temperature:options.temperature??.2,max_tokens:options.maxTokens??4096})});const d=await readResponse(r,provider),text=d?.choices?.[0]?.message?.content??d?.choices?.[0]?.text??'';if(!text)throw new ProviderError(provider,'استجابة المزود فارغة',502,true);return {text,usage:d.usage||null,raw:d};}
async function gemini({key,model,messages,options={}}){if(!key)throw new ProviderError('gemini','GEMINI_API_KEY غير موجود',401);const n=normalizeMessages(messages),system=n.find(x=>x.role==='system')?.content,contents=n.filter(x=>x.role!=='system').map(x=>({role:x.role==='assistant'?'model':'user',parts:Array.isArray(x.content)?x.content.map(p=>p.type==='image_url'?{inline_data:{mime_type:p.image_url.url.match(/^data:([^;]+)/)?.[1]||'image/png',data:p.image_url.url.split(',')[1]||''}}:{text:p.text||''}):[{text:x.content}]}));const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents,...(system?{systemInstruction:{parts:[{text:system}]}}:{}),generationConfig:{temperature:options.temperature??.2,maxOutputTokens:options.maxTokens??4096}})});const d=await readResponse(r,'gemini'),text=d?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'';if(!text)throw new ProviderError('gemini','استجابة Gemini فارغة',502,true);return {text,usage:d.usageMetadata||null,raw:d};}
async function workers(env,model,messages,options={}){if(!env?.AI?.run)throw new ProviderError('workers-ai','ربط Workers AI غير موجود',503);try{const d=await env.AI.run(model,{messages:normalizeMessages(messages),max_tokens:options.maxTokens??4096,temperature:options.temperature??.2}),text=d?.response??d?.choices?.[0]?.message?.content??'';if(!text)throw new ProviderError('workers-ai','استجابة Workers AI فارغة',502,true);return {text,usage:d.usage||null,raw:d};}catch(e){if(e instanceof ProviderError)throw e;throw new ProviderError('workers-ai',e.message||'فشل Workers AI',502,true);}}
export async function callProvider(env,modelId,messages,options={}){const s=getModel(modelId);if(!s)throw new ProviderError('catalog',`نموذج غير معروف: ${modelId}`,400);if(s.provider==='cerebras')return openAI({key:env.CEREBRAS_API_KEY,endpoint:'https://api.cerebras.ai/v1/chat/completions',model:s.model,messages,provider:'cerebras',options});if(s.provider==='gemini')return gemini({key:env.GEMINI_API_KEY,model:s.model,messages,options});if(s.provider==='workers-ai')return workers(env,s.model,messages,options);throw new ProviderError(s.provider,'مزود غير مدعوم',400);}
export async function routeCompletion(env,requestedModelId,messages,{fallbackModelId='cf-gpt-oss-20b',...options}={}){const requested=getModel(requestedModelId),start=Date.now();try{const r=await callProvider(env,requested.id,messages,options);return {...r,requested,actual:requested,fallback:false,latencyMs:Date.now()-start};}catch(primary){if(!fallbackModelId||fallbackModelId===requested.id||!primary.retryable)throw primary;const fallback=getModel(fallbackModelId),r=await callProvider(env,fallback.id,messages,options);return {...r,requested,actual:fallback,fallback:true,fallbackReason:primary.message,latencyMs:Date.now()-start};}}
