import { id, now, eventRecord } from './contracts.js';

const SAFE_LANGUAGES=new Set(['bash','sh','shell','python']);
export function detectToolProposal(text=''){const m=String(text).match(/```(bash|sh|shell|python)\s*\n([\s\S]*?)```/i);if(!m)return null;return {id:id('proposal'),kind:'terminal',language:m[1].toLowerCase(),command:m[2].trim(),requiresApproval:true,createdAt:now()};}
export function validateCommand(command,{maxLength=12000}={}){const value=String(command||'').trim();if(!value||value.length>maxLength)throw new Error('الأمر فارغ أو يتجاوز الحد المسموح');if(/[\u0000]/.test(value))throw new Error('الأمر يحتوي محارف غير صالحة');return value;}
export function approvalRecord({proposalId,approved,scope='single_run'}){return {id:id('approval'),proposalId,approved:Boolean(approved),scope,createdAt:now()};}
export function experimentRecord({chatId,proposal,approval}){if(!approval?.approved)throw new Error('لا يمكن إنشاء تجربة دون موافقة صريحة');if(approval.proposalId!==proposal.id)throw new Error('الموافقة لا تطابق الاقتراح');return {id:id('exp'),chatId,proposalId:proposal.id,command:validateCommand(proposal.command),language:proposal.language,status:'pending',output:'',exitCode:null,attempt:1,createdAt:now(),updatedAt:now()};}
export function verifyResult(experiment,{output='',exitCode=1}={}){const ok=Number(exitCode)===0;return {...experiment,status:ok?'completed':'failed',output:String(output).slice(0,50000),exitCode:Number(exitCode),updatedAt:now(),verified:ok};}
export function retryExperiment(experiment){if(experiment.status!=='failed')throw new Error('التجربة ليست فاشلة');if(experiment.attempt>=3)throw new Error('تم بلوغ الحد الأقصى لإعادة المحاولة');return {...experiment,status:'pending',attempt:experiment.attempt+1,output:'',exitCode:null,updatedAt:now()};}
export function experimentEvent(experiment,type,payload={}){return eventRecord({taskId:experiment.chatId,type,payload:{experimentId:experiment.id,...payload}});}
export function memoryToolStore(){const items=new Map(),events=[];return {async save(x){items.set(x.id,structuredClone(x));return x},async get(id){return structuredClone(items.get(id)||null)},async event(e){events.push(structuredClone(e));return e},async eventsFor(chatId){return events.filter(x=>x.taskId===chatId)}};}

export async function dispatchExperiment(env,experiment){if(!env.GITHUB_TOKEN)throw new Error('GITHUB_TOKEN غير مهيأ');const repo=env.GITHUB_REPO||'abdelrhym096290-ux/video-compressor-bot',workflow=env.GITHUB_WORKFLOW||'terminal.yml';const response=await fetch(`https://api.github.com/repos/${repo}/actions/workflows/${workflow}/dispatches`,{method:'POST',headers:{authorization:`Bearer ${env.GITHUB_TOKEN}`,accept:'application/vnd.github+json','content-type':'application/json','X-GitHub-Api-Version':'2022-11-28'},body:JSON.stringify({ref:env.GITHUB_REF||'main',inputs:{command:experiment.command,language:experiment.language,experimentId:experiment.id}})});if(!response.ok)throw new Error(`فشل إرسال التجربة إلى GitHub: HTTP ${response.status}`);return {...experiment,status:'dispatched',updatedAt:now()};}
export async function verifyWebhook(raw,signature,secret){if(!signature||!secret)return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(raw));const expected=Array.from(new Uint8Array(sig)).map(x=>x.toString(16).padStart(2,'0')).join('');const given=signature.replace(/^sha256=/,'');return expected.length===given.length&&expected.split('').every((x,i)=>x===given[i]);}
